CREATE TABLE IF NOT EXISTS students(
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '姓名',
    `age` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '年龄',
    `sex` CHAR(2) NOT NULL DEFAULT '女' COMMENT '性别',
    `created_time`  DATETIME NOT NULL DEFAULT '9999-12-31 23:59:59' COMMENT '新增时间',
    `updated_time` DATETIME NOT NULL DEFAULT '9999-12-31 23:59:59' COMMENT '更新时间' 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1001 COMMENT='学生表';
